class AuthError(Exception):
    """认证失败"""
